apiVersion: v1
kind: Service
metadata:
  name:kubeservice
spec:
  selector:
    app: kubeusers
  ports: 
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedeploy
spec: 
  replicas: 5
  selector:
    matchLabels:
      app: kubeusers
  template:
    metadata:
      app: kubeusers
    spec:
      conteiners:
        - name: test
          image: danielbustosjaime/test:1.0.0
          ports:
            - conteinerPort: 8080
            imagePullPolicy: Always


# y se ejecuta minikube con # kubectl apply -f kubeusers.yaml